version: "3"
services:
  ghostBlog:
    image: ghost:latest
    ports:
      - "60000:2368"
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    environment:
      url: http://localhost:60000
